---
title: "ccc"
author: "Pierre Nouvellet"
date: "2019-07"
---

```{r options, include = FALSE, message = FALSE, warning = FALSE, error = FALSE}
set.seed(1)
# runif(1,0,1)
library(knitr)



opts_chunk$set(collapse = TRUE)

opts_chunk$set(fig.path='figs/', fig.keep='high', 
               dev=c('png'), fig.width=8, fig.height=8, cache=FALSE,
               tidy=FALSE, warning=FALSE, fig.show="asis"
 	       )

# useful functions
sapply(paste0('Rscript/MCMC_Chain_bin/',(list.files('Rscript/MCMC_Chain_bin/'))),FUN = source)

```


NEED to do:
1) input

# Input

```{r}
n_size <- 1:6
N <- matrix(NA,length(n_size)+1,length(n_size)+1)
# size 1:
N[1,1] <- 0
N[1:2,1+1] <- 0
N[1:3,2+1] <- 0
N[1:4,3+1] <- c(17,8,3,2)
N[1:5,4+1] <- c(15,5,3,3,1)
N[1:6,5+1] <- c(3,4,2,2,1,0)
N[1:7,6+1] <- 0



```

# model check

```{r}

# n_size <- 1:6
B <- 1-.169  # escape from community
Q <- 1-.146  # escape from households

# define proba's for each households size

P <- matrix(NA,length(n_size)+1,length(n_size)+1)
# size 1:
P[1,1] <- 1
P[1:2,1+1] <- c(B,1-B) 
for (k in 2:length(n_size)){
  for (j in 0:(k-1)){
    P[j+1,k+1] <- choose(n = k, k = j) * P[ 1+j, 1+j] * B^(k-j) *Q^(j*(k-j))
  }
  P[k+1,k+1] <- 1-sum(P[1:k,k+1])
}

lambda_fct(n_s = n_size, theta = c(B,Q))
B^2
2*(1-B)*B*Q

```

# MCMC

```{r}

rep <- 1e3
theta0 <- c(.5, .5)
sigma_prop <- rep(.1,length(theta0))
prior_theta <- matrix(c(0,1), nrow = 2, ncol = 2, byrow = TRUE)

res <- MCMC_full(repli_adapt = 10, 
                 within_iter = rep/10, 
                 n_size = n_size,
                 N = N, 
                 iter = rep,
                 theta0 = theta0,
                 s = sigma_prop,
                 prior = prior_theta)


```

```{r}

Acc <- colSums(diff(res$theta)!=0)/rep          # acceptance rate (should be close to .2)
Acc

# plot traces
plot(res$logL[,1])                                  # of likelihood
layout(matrix(1:4,2,2,byrow = TRUE))
for (i in 1:length(theta0)) {
  plot(res$theta[,i],main = paste0(round(Acc[i]*100)),ylim = c(0,1) )        # of initial conditions
}

summary <- apply(res$theta,2,quantile, c(.5,.0275,.975))
summary
1-summary[1,]

summary_Ps <- array(data = NA,list(length(n_size)+1,length(n_size)+1,3))
for (k in 1:length(n_size)){
  for(j in 0:k){
    summary_Ps[j+1,k+1,1] <- quantile(res$Ps[j+1,k+1,],.5)
    summary_Ps[j+1,k+1,2] <- quantile(res$Ps[j+1,k+1,],.0275)
    summary_Ps[j+1,k+1,3] <- quantile(res$Ps[j+1,k+1,],.975)
  }
}
summary_Ps[,,1]

Expected <- summary_Ps[,,1] * matrix((colSums(N,na.rm=TRUE)),
                                     nrow = length(n_size)+1,length(n_size)+1,byrow = TRUE)

Expected
```